// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// @ts-ignore - directUrl is valid for Prisma 7
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
    // @ts-ignore - directUrl is valid for Prisma 7
    directUrl: process.env.DIRECT_URL,
  },
});
